### ISSUE TITLE
3.1 Update causes crashing on startup

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/ClimbLaddersFast#12]
Update 3.0.5 to 3.1 and a crash occurs on launch of aqm2

https://gist.github.com/itsdinkd/d2607533abacb143fb9cf8e355509283

**Comment by spoorn** [comment]
I made a mistake tagging the 3.1 versions for <= 1.19.2 because it's usually backwards compatible.  Untagged it on CurseForge.  Use 3.0.5/3.0.6 for <= 1.19.2
