### ISSUE TITLE
[REQUEST] Backport to 1.19.4

### ISSUE THREAD

**Issue by itsMarkiS** [spoorn/ClimbLaddersFast#16]
some things still havent updated to 1.20, most of the people still uses 1.19.4 nowadays, i was hoping we could have it xD

**Comment by spoorn** [comment]
the 1.19.3 version should work on 1.19.4.  I'll mark it on CurseForge.  I didn't really have to change anything for 1.20.1, so it should all be backwards and forwards compatible so far
