### ISSUE TITLE
climbladdersfast-4.0-1.20.1-forge.jar seems to be a fabric mod? 

### ISSUE THREAD

**Issue by PokeMaserJ** [spoorn/ClimbLaddersFast#17]
When using the CurseForge App, for some reason it's thinking this specific build is a Fabric mod, and thus is downloading Fabric API, and trying to disable said API disables this mod. You think that's on CurseForge's end, or yours?

**Comment by spoorn** [comment]
it's marked as Forge: https://legacy.curseforge.com/minecraft/mc-mods/climb-ladders-fast/files/4620430
so must be either a problem with CurseForge, or your modpack is set to the wrong modloader
