### ISSUE TITLE
cant climb down scaffolding when not looking down, it is ultra slow

### ISSUE THREAD

**Issue by itsMarkiS** [spoorn/ClimbLaddersFast#3]
self-explanatory... basically when you want to go down in a scaffolding you have to be pressing shift every block you go down while also looking down...

**Comment by spoorn** [comment]
The vanilla behavior stops you when you go down right?  I'd have to override that behavior

**Comment by spoorn** [comment]
Fixed in 3.0.3+ for 1.19 and 2.2.1+ for 1.18: https://www.curseforge.com/minecraft/mc-mods/climb-ladders-fast/files/all
