### ISSUE TITLE
Disable fast climb entirely on scaffolding

### ISSUE THREAD

**Issue by Baconbacon123** [spoorn/ClimbLaddersFast#4]
The fast climb feature makes scaffolding unusable for building while standing inside it. It would be nice to be able to disable the mod on scaffolding.

**Comment by spoorn** [comment]
Added in 3.0.4+ for 1.19, 2.2.2+ for 1.18: https://www.curseforge.com/minecraft/mc-mods/climb-ladders-fast/files/all
